kafka:
  bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS}
  transaction_timeout_ms: 60000

topics:
  - source_id: his_mysql_01
    table: patients
    topic: cdc.his.patients
    partition_count: 3
    partition_key_field: patient_id

  - source_id: his_mysql_01
    table: visits
    topic: cdc.his.visits
    partition_count: 3
    partition_key_field: visit_id

  - source_id: his_mysql_01
    table: orders
    topic: cdc.his.orders
    partition_count: 3
    partition_key_field: order_id

  - source_id: lis_sqlserver_01
    table: lab_results
    topic: cdc.lis.lab_results
    partition_count: 3
    partition_key_field: result_id

default_topic_pattern: "cdc.{database}.{table}"

sink:
  pg_dsn: "postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:5432/${PG_DATABASE}?sslmode=disable"
  dedup_retention_hours: 168    # 7天
